//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sioservice", ConfigurationName="ServiceReference1.sioservicePort")]
    public interface sioservicePort {
        
        [System.ServiceModel.OperationContractAttribute(Action="connectAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        string connect(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="connectAction", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        System.Threading.Tasks.Task<string> connectAsync(string login, string password);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Easyservice) du message exportOffreRequest ne correspond pas à la valeur par défaut (urn:sioservice)
        [System.ServiceModel.OperationContractAttribute(Action="exportOffreAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WindowsFormsApp1.ServiceReference1.exportOffreResponse exportOffre(WindowsFormsApp1.ServiceReference1.exportOffreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="exportOffreAction", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.exportOffreResponse> exportOffreAsync(WindowsFormsApp1.ServiceReference1.exportOffreRequest request);
        
        // CODEGEN : La génération du contrat de message depuis l'espace de noms de wrapper (urn:Easyservice) du message exportCandidRequest ne correspond pas à la valeur par défaut (urn:sioservice)
        [System.ServiceModel.OperationContractAttribute(Action="exportCandidAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WindowsFormsApp1.ServiceReference1.exportCandidResponse exportCandid(WindowsFormsApp1.ServiceReference1.exportCandidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="exportCandidAction", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.exportCandidResponse> exportCandidAsync(WindowsFormsApp1.ServiceReference1.exportCandidRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportOffre", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportOffreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string id;
        
        public exportOffreRequest() {
        }
        
        public exportOffreRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportOffreResponse", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportOffreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xml;
        
        public exportOffreResponse() {
        }
        
        public exportOffreResponse(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCandid", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportCandidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string id;
        
        public exportCandidRequest() {
        }
        
        public exportCandidRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCandidResponse", WrapperNamespace="urn:Easyservice", IsWrapped=true)]
    public partial class exportCandidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xml;
        
        public exportCandidResponse() {
        }
        
        public exportCandidResponse(string xml) {
            this.xml = xml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sioservicePortChannel : WindowsFormsApp1.ServiceReference1.sioservicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sioservicePortClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.sioservicePort>, WindowsFormsApp1.ServiceReference1.sioservicePort {
        
        public sioservicePortClient() {
        }
        
        public sioservicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sioservicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sioservicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sioservicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string connect(string login, string password) {
            return base.Channel.connect(login, password);
        }
        
        public System.Threading.Tasks.Task<string> connectAsync(string login, string password) {
            return base.Channel.connectAsync(login, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.exportOffreResponse WindowsFormsApp1.ServiceReference1.sioservicePort.exportOffre(WindowsFormsApp1.ServiceReference1.exportOffreRequest request) {
            return base.Channel.exportOffre(request);
        }
        
        public string exportOffre(string id) {
            WindowsFormsApp1.ServiceReference1.exportOffreRequest inValue = new WindowsFormsApp1.ServiceReference1.exportOffreRequest();
            inValue.id = id;
            WindowsFormsApp1.ServiceReference1.exportOffreResponse retVal = ((WindowsFormsApp1.ServiceReference1.sioservicePort)(this)).exportOffre(inValue);
            return retVal.xml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.exportOffreResponse> WindowsFormsApp1.ServiceReference1.sioservicePort.exportOffreAsync(WindowsFormsApp1.ServiceReference1.exportOffreRequest request) {
            return base.Channel.exportOffreAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.exportOffreResponse> exportOffreAsync(string id) {
            WindowsFormsApp1.ServiceReference1.exportOffreRequest inValue = new WindowsFormsApp1.ServiceReference1.exportOffreRequest();
            inValue.id = id;
            return ((WindowsFormsApp1.ServiceReference1.sioservicePort)(this)).exportOffreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.exportCandidResponse WindowsFormsApp1.ServiceReference1.sioservicePort.exportCandid(WindowsFormsApp1.ServiceReference1.exportCandidRequest request) {
            return base.Channel.exportCandid(request);
        }
        
        public string exportCandid(string id) {
            WindowsFormsApp1.ServiceReference1.exportCandidRequest inValue = new WindowsFormsApp1.ServiceReference1.exportCandidRequest();
            inValue.id = id;
            WindowsFormsApp1.ServiceReference1.exportCandidResponse retVal = ((WindowsFormsApp1.ServiceReference1.sioservicePort)(this)).exportCandid(inValue);
            return retVal.xml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.exportCandidResponse> WindowsFormsApp1.ServiceReference1.sioservicePort.exportCandidAsync(WindowsFormsApp1.ServiceReference1.exportCandidRequest request) {
            return base.Channel.exportCandidAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.exportCandidResponse> exportCandidAsync(string id) {
            WindowsFormsApp1.ServiceReference1.exportCandidRequest inValue = new WindowsFormsApp1.ServiceReference1.exportCandidRequest();
            inValue.id = id;
            return ((WindowsFormsApp1.ServiceReference1.sioservicePort)(this)).exportCandidAsync(inValue);
        }
    }
}
